apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pull
  namespace: libreplay-staging
  labels:
    app.kubernetes.io/name: libreplay
    libreplay.e-dani.com/environment: staging
spec:
  refreshInterval: 6h
  secretStoreRef: { name: onepassword, kind: ClusterSecretStore }
  target:
    name: harbor-pull
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef: { key: infra-harbor-k8s-runtime-pull/dockerconfigjson }
