apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: libreplay-staging
resources:
  - ../../../k8s
  - harbor-pull.externalsecret.yaml

patches:
  - path: patch-namespace.json
    target:
      kind: Namespace
      name: libreplay
  - path: patch-external-secret.json
    target:
      kind: ExternalSecret
      name: libreplay-secrets
  - path: patch-configmap.yaml
  - path: patch-postgres-db.yaml
  - path: patch-required-provider-secrets.yaml
  - path: patch-ingressroute.json
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: libreplay-lan
  - path: patch-staging-job-annotations.yaml
