apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: libreplay-staging
resources:
  - ../../k8s

patches:
  - path: patches/namespace.json
    target:
      kind: Namespace
      name: libreplay
  - path: patches/external-secret.json
    target:
      kind: ExternalSecret
      name: libreplay-secrets
  - path: patches/configmap.yaml
  - path: patches/postgres-db.yaml
  - path: patches/required-provider-secrets.yaml
  - path: patches/ingressroute.json
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: libreplay-lan
  - path: patches/staging-job-annotations.yaml
